### ISSUE TITLE
Invalid op launching steam

### ISSUE THREAD

**Issue by duckfromdiscord** [danoon2/Boxedwine#104]
When launching steam, it says `Invalid op: loadSeg rm=f1` and restarts.

**Comment by danoon2** [comment]
steam is on my list of things to get working.  I've gotten pretty far, but I think I need to get gecko working first since steam seems to rely heavily on an embedded web browser.

**Comment by duckfromdiscord** [comment]
Awesome to hear that Steam is planned! Is gecko what's causing the invalid op error?

**Comment by duckfromdiscord** [comment]
In fact, this issue is invalid altogether since the issue no longer exists in the winex11 branch I built from source.

**Comment by danoon2** [comment]
@duckfromdiscord With the new tiny core based file system, I made an effort with Gecko.  I tried to get all of the dependencies, like certificates, ssl, etc.  So it definitely gets farther, but so far I haven't see it render a page yet.

**Comment by duckfromdiscord** [comment]
I think curl is missing an openssl.so

**Comment by danoon2** [comment]
@duckfromdiscord thanks, if you delete the 9.18 file system and re download it it, ssl 3 should now be included.  You will need to delete the previous container or use a new container to see the changes.

**Comment by danoon2** [comment]
@duckfromdiscord I tried Steam again, might be the first time with x11 emulation.  It gets pretty far, steamwebhelper doesn't start thought, but I see the black UI that asks if I want to try again.  While its loading I see it probing other processes, but I didn't implement those /proc interfaces so I wonder if that is it.

**Comment by duckfromdiscord** [comment]
> you delete the 9.18 file system and re download it

Apparently you have to delete the zip from the cache otherwise it re-downloads instantly when you click install. Just a note to myself.

![image](https://github.com/user-attachments/assets/2b89aa46-8aa6-4371-9fb9-06519c421a8f)

Now it says this every time. This happened once before, but happens on every run now.
