### ISSUE TITLE
Build instructions for MacOS

### ISSUE THREAD

**Issue by RobBW** [danoon2/Boxedwine#15]
The instructions at http://www.boxedwine.org/documentation/build/ do not work for MacOS.
The svn download link https://svn.code.sf.net/p/boxedwine/code/trunk boxedwine-code is not working.
When I did get a download from ~ /trunk/boxedwine/cpp/project/mac-xcode I could not find a buildMac.sh to use.
Did you really mean to run that command on the linux file?

**Comment by danoon2** [comment]
Sorry about that.  Those instructions were out of date.  You can clone or download the Boxedwine source code directly from GitHub then open the workspace with XCode at project\mac-xcode\Boxedwine.xcworkspace.  I updated the instructions at http://www.boxedwine.org/documentation/build/ to reflect this.

I'm actively working on the Mac build and for the most part it works well, but sound might be choppy.  I'm hoping to make a native CoreAudio implementation of the sound code for Mac in the next couple of weeks.

**Comment by Gcenx** [comment]
Also remember to change the developer ID to your own or to run locally.

**Comment by RobBW** [comment]
Thanks for your quick response. I will try it again in the next few weeks.
Regards
Rob Wilkinson
***@***.***
