### ISSUE TITLE
Death Drome crash

### ISSUE THREAD

**Issue by siriusinko** [danoon2/Boxedwine#16]
Game crash after beginning. Is this not accidentally related to the fact that the menu appears first, and then the game should start in another window? I run it with the -p3 argument, because I have an amd processor.
And it also seems that vsync doesn't work in games. It should limit to 60 frames per second, right? I've tried games and have different values ​​everywhere but never 60.

**Comment by danoon2** [comment]
Are you using the UI or command line?  If you are using the UI, go to the container and find "Storage Location", 7th down on the right when you select your game in the container tab.  On the right of "Storage Location", there is an open button.  Click on that then open "lastLog.txt" in that folder.  That file will contain some information that might help.  You can paste it here.  If you are using the command line, just paste the output here.

What build/OS are you using?

As for the -p3 command line argument, you probably never need to use that, it only changes what the CPUID instruction will report to the game.  

As for VSync, that only works with DirectX and OpenGL games.  For games that draw directly to the screen it does nothing.  I did implement a new feature called skip frames for the next release that will ignore screen updates that happen more than the frame rate you specify, but this is mainly for testing, I'm not sure it will have much effect other than maybe saving some CPU time.
![log](https://user-images.githubusercontent.com/54689747/117686727-00076100-b16c-11eb-9c0b-f3b5e3d6d7d3.jpg)

**Comment by siriusinko** [comment]
Hmm ... I couldn't find the lastlog file. Forgot to mention, I didn't install the game, I used the demo from archive.org
I just mounted the folder in Boxedwine. I'm using the latest Boxedwine build. OS win 10 20H2
![изображение_2021-05-10_194414](https://user-images.githubusercontent.com/38426934/117694687-180cce00-b1c8-11eb-9ef6-ed14f740accf.png)

**Comment by danoon2** [comment]
Are you running the latest build 20.1.2?

https://sourceforge.net/projects/boxedwine/files/Builds/20.1.2/BoxedWine%2020.1.2%20-%20Windows.zip/download

That release comes with a 32-bit and 64-bit build.  Did you try both builds?  They actually use completely different CPU emulators.   The 32-bit version is much slower, but more stable.

**Comment by siriusinko** [comment]
Yes, I use version 20.1.2 I tried 32 bit but nothing changed. Does the game work for you? Or haven't you tried it yet?

**Comment by siriusinko** [comment]
For me, this is also important because the game does not run on processors other than Intel. There is a patch that fixes this, but it has a side effect - the sound disappears.
