### ISSUE TITLE
可以直接发布APK吗

### ISSUE THREAD

**Issue by aini3225** [danoon2/Boxedwine#18]
能发布手机能用的APK安装包吗？

**Comment by danoon2** [comment]
"Can you publish an APK installation package that can be used by mobile phones?"

No, currently this does not support mobile.  It probably wouldn't be fast enough for most games and I would need to figure out how to handle mouse and keyboard stuff with a touch screen.  I know there are some dosbox ports out there, maybe in the future I can see how they handled the mouse and keyboard after I get a faster x86 -> Arm emulation working.
