### ISSUE TITLE
Problem with mount disk

### ISSUE THREAD

**Issue by siriusinko** [danoon2/Boxedwine#19]
I tried to mount in 2 ways: a virtual cd drive (daemon tools) and a completely copied game folder from the disk itself. No way works, what am I missing? The games still warn me that I have to mount the disk, I can't figure out what the problem is.

**Comment by danoon2** [comment]
Sounds like the game expects to find some files on a CD.  Boxedwine doesn't support CD's yet.  So if the game does any kind of CD check that won't work.

Adding support for ISO's is on my todo list

https://github.com/danoon2/Boxedwine/wiki/Roadmap-Features

Eventually I would like Boxedwine to be able to mount the host CD drive (either physical or mounted), and also handle ISO and BIN/CUE files directly, like being able to drag an ISO into the UI and have it automatically mount it and and run an installer.

**Comment by siriusinko** [comment]
OK, thanks for answer.
