### ISSUE TITLE
Issue while generating Cmake 

### ISSUE THREAD

**Issue by JuliPi** [danoon2/Boxedwine#2]
When i tried to compile Boxedwine with Cmake, i got this issue. Are there any fixes?
![image](https://user-images.githubusercontent.com/52183402/114994886-8dbd9c80-9e9d-11eb-8ab1-bf60d6c586b3.png)

**Comment by danoon2** [comment]
On Windows you need to open the project using Visual Studio 2019.  There is a free version call Visual Studio Community, which is what I used.  https://visualstudio.microsoft.com/vs/community/

The project file is located:
project\msvc\BoxedWine\BoxedWine.sln
