### ISSUE TITLE
Is printer support possible?

### ISSUE THREAD

**Issue by emptythevoid** [danoon2/Boxedwine#20]
Is there a way to enable printer support?

**Comment by danoon2** [comment]
It would be possible to add support for printing, but at this point I have no plans to implement that.  I'm not sure how hard it would be, but I would expect several weeks of work to implement an emulated printer driver that forwards its print request to the host computer's printer.

**Comment by emptythevoid** [comment]
Thanks for the quick response. I understand. To give context, I was hoping to be able to use Boxedwine to run an old Windows document analyzer tool on Windows 10, and I think this is the only thing stopping this solution. But I completely understand.
