### ISSUE TITLE
File access errors in web version using Emscripten 2.0.25

### ISSUE THREAD

**Issue by tech234a** [danoon2/Boxedwine#28]
Hi!

I can't seem to compile a functional version of Boxedwine for Emscripten... every time I try and launch it I get a bunch of file access errors ultimately leading to Javascript exception in console.

I've tried compiling the Emscripten version of this project using Emscripten 2.0.26 and 2.0.25 (in case #27 was the cause of my issue, compiling with the lower version gave me different error messages but still failed to initialize).

Console output from the 2.0.25 build:
```
Unable to delete:/lib/wine/wineboot.exe.so error:Error: ENOENT: No such file or directory., '/lib/wine/wineboot.exe.so'
creating: root/base/opt/wine/lib/libwine.so.1.link
FATAL ERROR: Error: FS error
FATAL ERROR: Error: EEXIST: File exists., '/'
FATAL ERROR: Error: Error: EEXIST: File exists., '/'
```

I've been trying to launch Boxedwine HTML using an instance hosted on a local HTTP server using http://localhost:8000/boxedwine.html?root=debian10.zip&overlay=Wine-5.0.zip.

What am I doing wrong?

**Comment by tech234a** [comment]
The issue appears to be with the overlays feature, combining the overlays into a single ZIP filesystem seems to solve the problem as described in https://github.com/danoon2/Boxedwine/issues/25#issuecomment-872264555. I'll keep this issue open for now just to ensure that my understanding that the overlay feature is broken is correct.

**Comment by kevodwyer** [comment]
Hi,
Good to hear you were able to combine the debian + wine files together and it worked.
Previously they were published as a merged filesystem, since then the desktop version has matured greatly.

The overlay feature is designed for replacing WINE DLLs, adding fonts, game saves etc. That works fine in my testing.
