### ISSUE TITLE
Graphics are upside down in linux 64-bit build

### ISSUE THREAD

**Issue by aqrit** [danoon2/Boxedwine#33]
Launching say regedit.exe, shows the screen to be mirrored vertically.

Undefining `BOXEDWINE_LINUX` in `./project/linux/build64.sh` seems to eliminate this issue. 

This is using the current (8f7b18e213dc0ecc9c49494e553eea3ff7ca6a69) tarball of the master branch.

**Comment by danoon2** [comment]
I guess this is the issue with testing so many platforms at once, I left a change on one computer and it didn't make it to git.  At first this issue confused me because I did a lot of testing on Linux with this.

Everything should be working now.

**Comment by aqrit** [comment]
Seems to work. Thanks!
