### ISSUE TITLE
Make build scripts readable

### ISSUE THREAD

**Issue by yochananmarqos** [danoon2/Boxedwine#38]
Please split build flags instead of a huge one-liner in the build scripts.

Example:
```
  cmake -H../../lib/poco -B./linux_build \
    -DENABLE_SEVENZIP=OFF \
    -DENABLE_XML=OFF \
    -DENABLE_JSON=OFF \
...
```

**Comment by danoon2** [comment]
@yochananmarqos Thanks for the suggestion, I think that is a good idea to make it easier to read and also see diffs better.  I updated the 4 Linux build scripts.
