### ISSUE TITLE
why cmd run console and run as window?

### ISSUE THREAD

**Issue by MUHAMMED1405** [danoon2/Boxedwine#68]
I am trying to run some commands on cmd but it not open it just says to me in console:
`Starting ...
Command line arguments: "./this.program" "-root" "/root/base" "-mount_drive" "/root/files/" "d" "-nozip" "/bin/wine" "cmd"
Using root directory: /root/base
Launching "/bin/wine" "cmd" 
boxeddrv_ClipCursor not implemented
wine_notify_icon not implemented
boxeddrv_SetWindowStyle not implemented
boxeddrv_SetWindowStyle not implemented
boxeddrv_ClipCursor not implemented
wine_notify_icon not implemented
failed to remove file: errno=31
failed to remove file: errno=31
failed to remove file: errno=31
failed to remove file: errno=31
failed to remove file: errno=31
failed to remove file: errno=31
wine_notify_icon not implemented
wine_notify_icon not implemented
wine_notify_icon not implemented
wine_notify_icon not implemented
wine: configuration in L"/home/username/.wine" has been updated.
boxeddrv_ClipCursor not implemented
Microsoft Windows 6.1.7601`
I am using the Emscripten version and also i trying to type but nothing show.

**Comment by danoon2** [comment]
Instead of "cmd", try "wineconsole"

**Comment by MUHAMMED1405** [comment]
thanks that works
