### ISSUE TITLE
Internet Proxy and Password protected zips

### ISSUE THREAD

**Issue by krum110487** [danoon2/Boxedwine#73]
Hello!

I have a very specific use case to run an older program. I want to prevent false positives that the program has.

I need to proxy the requests from the app to local files. Is it possible to set the proxy on boxedwine? 

The other question I have is: Does boxedwine allow for password protected zips? Or can it mount a virtual drive?

Thanks!!

**Comment by danoon2** [comment]
I have not implemented support for password protected zip files, but you can mount a directory to show up as a particular drive in Wine

-mount_drive “c:\my games” d

This is also available in the Boxedwine UI in the Containers tab

By proxy, to you mean a network proxy?  Or some way to redirect file requests?

For file redirection, that is supported at the directory level

-mount “c:\my games” “/home/username/my games”
or
-mount “c:\my games\mygame.zip” “/home/username/my games”

**Comment by krum110487** [comment]
Hello,

Thank you for responding the biggest problem with a drive or a regular zip is that virus scanners will still scan them unless they are password protected. Or in a format they cannot scan directly. But that answers that one!

As for the proxy, I mean network proxy, is there a easy way to tell the emulated linux system to proxy traffic to the host via localhost?

Thanks!

**Comment by danoon2** [comment]
The networking stuff is still pretty limited.  I've had some luck with it, can even play World of Warcraft for 30 seconds.  But I haven't spent much time on getting it to really work well.  I'm not even sure what would be involved to make it work with a proxy.

As for you virus scan problem, that is an interesting problem.  I don't think it would be too hard to make work if you or someone would be willing to implement it.   But my todo list on this project is already way too big so I wouldn't be able to get to something like that for a long time.

**Comment by krum110487** [comment]
I understand! I would probably be able to make the password part work, but it isn't really a priority for me if the networking isn't there, which would be required for my needs.

I would help with code, but I haven't worked in C or C++ in many years and I am very rusty. (not to mention the part where emulation is very intimidating to me) Thank you for all your hard work. I would like to one day look through your code and see if I can even understand what is going on.

Thank you for responding!

**Comment by ludaka** [comment]
> The networking stuff is still pretty limited. I've had some luck with it, can even play World of Warcraft for 30 seconds. But I haven't spent much time on getting it to really work well. I'm not even sure what would be involved to make it work with a proxy.
> 
> As for you virus scan problem, that is an interesting problem. I don't think it would be too hard to make work if you or someone would be willing to implement it. But my todo list on this project is already way too big so I wouldn't be able to get to something like that for a long time.

hey do you remember how do you run wow bcs im truing to run  wow 3.3.5 on boxedwine version from early 2025 and even on lastest but game crash after login before character screen to appear ..

**Comment by danoon2** [comment]
Its been a long time since I tried that game.  I'm happy to see that it worked and the networking seems way more stable now.

I played for about 10 minutes on 25R1 x64 Windows without any issue.  Which platform are you using?

<img width="2052" height="1600" alt="Image" src="https://github.com/user-attachments/assets/5f6ac1ec-33dd-42dc-9d92-ed3d2f0a0952" />

**Comment by ludaka** [comment]
> Its been a long time since I tried that game. I'm happy to see that it worked and the networking seems way more stable now.
> 
> I played for about 10 minutes on 25R1 x64 Windows without any issue. Which platform are you using?
> 
> <img alt="Image" width="2000" height="1600" src="https://private-user-images.githubusercontent.com/54689747/552956994-5f6ac1ec-33dd-42dc-9d92-ed3d2f0a0952.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzE2NjU0MzAsIm5iZiI6MTc3MTY2NTEzMCwicGF0aCI6Ii81NDY4OTc0Ny81NTI5NTY5OTQtNWY2YWMxZWMtMzNkZC00MmRjLTlkOTItZWQzZDJmMGEwOTUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjAyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwMjIxVDA5MTIxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjZjkwZTk1ZDljNzViMDlkOWFiYjFkOTJlNGVmN2Q1YTgxZDEzZGU1OTA4ZDFhM2IwNzljMjMyNmQ4MzRkMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.v4eTLwrQBQI5-RnMbOQNsnAUVAKmLztWhFv4RhV7EPg">

its on Win11 x64 with ryzen 3200 and amd rx 470 gpu with wine 6 i tried on different pc and none worked ( always crash before characters to appear ) this is the log before game crash also i tried to run game with -opengl it give ''unable to start 3d aceleration'' .. tested it with 4.3.4 and same happen again it crash before character screen

 i saw errors like this during initial game lauching : 0024:err:winediag:wined3d_dll_init The GLSL shader backend has been disabled. You get to keep all the pieces if it breaks.

**Comment by danoon2** [comment]
I tested 25R1 x64 Windows with a software OpenGL implementation and that worked too.  You can try this from the UI

<img width="2006" height="1227" alt="Image" src="https://github.com/user-attachments/assets/be32b352-521b-4ab4-a684-2a2847a81a42" />

If that works then its your graphics driver OpenGL.  OpenGL isn't aging very well and Wine is moving toward Vulkan.  Boxedwine's Vulkan support is still far from perfect so hopefully one of the Mesa OpenGL drivers Boxedwine supports in the UI will work.
