### ISSUE TITLE
Can't install Kellogg's Mission Nutrition: DirectX folder not found

### ISSUE THREAD

**Issue by MrYdse** [danoon2/Boxedwine#8]
Hi, I've been trying to install Kellogg's Mission Nutrition using Boxedwine for a while now, and after finding out it needed Win95 or 98, I found that it also needs a version of DirectX. In the error message it specifies no more than that "DirectX folder could not be found". I've tried running Wine Config and adding d3d9, d3d9, d3d10, d3d11, d3d12, d3dx9_43, d3dx10_43, d3dx11_43, and d2d1, all to no effect. I'm not sure what else I can try.

A link to the game for reproduction:  [https://archive.org/details/MissionNutritionKelloggs](https://archive.org/details/MissionNutritionKelloggs)

If anyone else is able to install and run the game, please tell me how. I would appreciate it greatly, as I have a nostalgic bond to the game.

**Comment by danoon2** [comment]
Who ever uploaded that ISO probably removed some stuff to keep the size down.  A lot of setups come with DirectX folders and this one seems to have been removed.  I don't know if you will be able to fix this or now.  I might require a specific DirectX installer in that folder and maybe some other stuff was removed too.
