### ISSUE TITLE
Cannot install `dxvk_1101`

### ISSUE THREAD

**Issue by duckfromdiscord** [danoon2/Boxedwine#86]
I can't install `dxvk` latest because it requires Wine 7.0, but with `dxvk_1101` (1.10.1) I have this issue:
```
Loaded ...\Boxedwine\FileSystems\winetricks.zip in 224 ms
Loaded ...\Boxedwine\FileSystems\Wine-6.0.zip in 39 ms
Launching "/bin/sh" "/usr/bin/winetricks" "dxvk1101" 
Executing mkdir -p /home/username
Using winetricks 20220411-next - sha256sum: ... with wine-6.0 and WINEARCH=win32
Executing w_do_call dxvk1101
Executing mkdir -p /home/username
Executing load_dxvk1101 
Executing mkdir -p /home/username/.cache/winetricks/dxvk1101
Executing cd /home/username/.cache/winetricks/dxvk1101
Downloading https://github.com/doitsujin/dxvk/releases/download/v1.10.1/dxvk-1.10.1.tar.gz to /home/username/.cache/winetricks/dxvk1101
...
Executing cd /home/username
------------------------------------------------------
warning: Please refer to dxvk version 1.10.1 release notes... See: https://github.com/doitsujin/dxvk/releases/tag/1.10.1
------------------------------------------------------
------------------------------------------------------
warning: Please refer to current dxvk base graphics driver requirements... See: https://github.com/doitsujin/dxvk/wiki/Driver-support
------------------------------------------------------
Executing cd /home/username/.wine/dosdevices/c:/windows/temp
Executing tar -zxf /home/username/.cache/winetricks/dxvk1101/dxvk-1.10.1.tar.gz
tar (child): gzip: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
/bin/tar: Child returned status 2
/bin/tar: Error is not recoverable: exiting now
------------------------------------------------------
warning: Note: command tar -zxf /home/username/.cache/winetricks/dxvk1101/dxvk-1.10.1.tar.gz returned status 2. Aborting.
------------------------------------------------------
Boxedwine has shutdown
```

**Comment by danoon2** [comment]
Thanks for testing that.  Winetricks is very experimental and probably won't be included in the next official release.  But it is fun to play with and I think will be very useful.  

Looks like I forgot to include gzip in the winetricks filesystem.

**Comment by duckfromdiscord** [comment]
> Winetricks is very experimental and probably won't be included in the next official release. But it is fun to play with and I think will be very useful.

I like being able to install winetricks, perhaps you could have an option to enable it but keep that off by default in the next stable release. Unless that's what you mean.

> Thanks for testing that. [...] Looks like I forgot to include gzip in the winetricks filesystem.

No problem! I'll report bugs I find so I can help out that way.

Is there a way for me to add `gzip` myself?

**Comment by duckfromdiscord** [comment]
I added `gzip` to `/bin` in the filesystem zip file and it's the same error. Strange.

**Comment by duckfromdiscord** [comment]
> I added `gzip` to `/bin` in the filesystem zip file and it's the same error. Strange.

Disregard this; it used my backup winetricks filesystem with a different filename instead of the original winetricks filesystem I edited.

I copied `gzip` from a fresh 32-bit Debian install and got `/bin/gzip: /lib/i386-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /bin/gzip)` so I'll have to figure out which libc version the winetricks FS uses.

**Comment by duckfromdiscord** [comment]
This was fixed in the X11 branch.
