### ISSUE TITLE
(Documentation request) Move the wiki to README sections

### ISSUE THREAD

**Issue by hardBSDk** [danoon2/Boxedwine#96]
The wiki can only be edited by the repository maintainers, while the README can receive PRs from anyone.

I can do this for you if you accept the request.

**Comment by danoon2** [comment]
Sorry its taken me a bit to get back.  I wanted to research this.  I see what you mean how the wiki has a git repository, but it seems like its only useful for making a backup.  I see lots of back and forth on stackoverflow with pros and cons for moving away from the wiki page.

I'm curious if this is what you meant, something like a docs section which I started a while back

https://github.com/danoon2/Boxedwine/blob/master/docs/CPUemulation.md

**Comment by hardBSDk** [comment]
@danoon2 It don't need to be the README but any documentation file on the repository, it will allow any contributor to improve the documentation without a repository maintainer role.

(I need this to improve the documentation)

**Comment by hardBSDk** [comment]
@danoon2 Read the message again "the file **you** sent"

I want to move these two wiki sections to repository files:

- https://github.com/danoon2/Boxedwine/wiki/How-build-Wine
- https://github.com/danoon2/Boxedwine/wiki/Performance

But the ideal is to move everything and disable the wiki, the contributors should read the documentation files from the README.

**Comment by danoon2** [comment]
@hardBSDk  Ok, I think I get it now.  You want to create a pull request to add those 2 wiki sections to a file and you were asking if I'd be ok with that before you did it.

Yes, I think that is a good idea and I will approve any requests to move those to the boxedwine repro.

**Comment by hardBSDk** [comment]
@danoon2 Thanks a lot, can I move all sections?

**Comment by danoon2** [comment]
@hardBSDk yes, and thank you for helping.

**Comment by hardBSDk** [comment]
@danoon2 It's done, once you merge my PR I will improve the documentation.

https://github.com/danoon2/Boxedwine/pull/100
