### ISSUE TITLE
Need help: Boxedwine has an error with File Exists "/" while trying to load any program

### ISSUE THREAD

**Issue by NarmakTwo** [danoon2/Boxedwine#97]
I'm trying to run a retro windows game through Boxedwine through Emscripten, but once it loads all the initilizations, I get error: FATAL ERROR: Error: Error: EEXIST: File exists., '/'. There are no tutorials online that actually show how to do what I'm trying to do and I don't know how to fix this. It's all properly compiled and I just want to load http://wsl.localhost:8000/boxedwine.html?p=cmd.exe&desktop=shell as a test. It even has the filesystem zip with a files directory with my app. Please help!

Stackoverflow link: https://stackoverflow.com/questions/78715765/boxedwine-has-an-error-with-file-exists-while-trying-to-load-cmd

**Comment by danoon2** [comment]
If you click on the continuous integration checkmark on the main github page for boxedwine, it will bring you to Jenkins.  From there you can download the latest development build which includes the Emscripten build with a test page.

![boxedwine](https://github.com/danoon2/Boxedwine/assets/54689747/55cca7a1-7e8d-4546-8ef7-a6451b1e7741)

Direct Link

http://208.113.165.28:8080/job/Boxedwine/job/master/

Currently I'm using Emscripten 3.1.29

I've tried a more recent version, 3.1.61, but had some issues.  I wonder if that is what you are seeing.

**Comment by NarmakTwo** [comment]
It works now. Thanks so much!

**Comment by NarmakTwo** [comment]
also, how would i go about using wine64 here?

**Comment by danoon2** [comment]
@NarmakTwo  unfortunately, I only support 32-bit emulation.  That would require entirely new CPU emulation code and Linux kernel emulation.

**Comment by NarmakTwo** [comment]
alr thanks anyways

**Comment by NarmakTwo** [comment]
Just found out that it was because I was running it through WSL but used File Explorer to add the executable to the filesystem zip. I think it happened because I had to unzip it, then add, then recompress, and the recompressed zip was in the windows filesystem (NTFS)
